# encoding: UTF-8
# This file is auto-generated from the current state of the database. Instead
# of editing this file, please use the migrations feature of Active Record to
# incrementally modify your database, and then regenerate this schema definition.
#
# Note that this schema.rb definition is the authoritative source for your
# database schema. If you need to create the application database on another
# system, you should be using db:schema:load, not running all the migrations
# from scratch. The latter is a flawed and unsustainable approach (the more migrations
# you'll amass, the slower it'll run and the greater likelihood for issues).
#
# It's strongly recommended that you check this file into your version control system.

ActiveRecord::Schema.define(version: 20140204062020) do

  create_table "pages", force: true do |t|
    t.datetime "created_at"
    t.datetime "updated_at"
    t.string   "home_slideshow_img1_file_name"
    t.string   "home_slideshow_img1_content_type"
    t.integer  "home_slideshow_img1_file_size"
    t.datetime "home_slideshow_img1_updated_at"
    t.string   "home_slideshow_img2_file_name"
    t.string   "home_slideshow_img2_content_type"
    t.integer  "home_slideshow_img2_file_size"
    t.datetime "home_slideshow_img2_updated_at"
    t.string   "home_slideshow_img3_file_name"
    t.string   "home_slideshow_img3_content_type"
    t.integer  "home_slideshow_img3_file_size"
    t.datetime "home_slideshow_img3_updated_at"
    t.string   "home_slideshow_img4_file_name"
    t.string   "home_slideshow_img4_content_type"
    t.integer  "home_slideshow_img4_file_size"
    t.datetime "home_slideshow_img4_updated_at"
    t.string   "home_slideshow_img5_file_name"
    t.string   "home_slideshow_img5_content_type"
    t.integer  "home_slideshow_img5_file_size"
    t.datetime "home_slideshow_img5_updated_at"
    t.string   "home_slideshow_img6_file_name"
    t.string   "home_slideshow_img6_content_type"
    t.integer  "home_slideshow_img6_file_size"
    t.datetime "home_slideshow_img6_updated_at"
    t.string   "home_slideshow_img7_file_name"
    t.string   "home_slideshow_img7_content_type"
    t.integer  "home_slideshow_img7_file_size"
    t.datetime "home_slideshow_img7_updated_at"
    t.string   "home_slideshow_img8_file_name"
    t.string   "home_slideshow_img8_content_type"
    t.integer  "home_slideshow_img8_file_size"
    t.datetime "home_slideshow_img8_updated_at"
    t.string   "home_slideshow_img9_file_name"
    t.string   "home_slideshow_img9_content_type"
    t.integer  "home_slideshow_img9_file_size"
    t.datetime "home_slideshow_img9_updated_at"
    t.string   "home_slideshow_img10_file_name"
    t.string   "home_slideshow_img10_content_type"
    t.integer  "home_slideshow_img10_file_size"
    t.datetime "home_slideshow_img10_updated_at"
    t.string   "concept_img1_file_name"
    t.string   "concept_img1_content_type"
    t.integer  "concept_img1_file_size"
    t.datetime "concept_img1_updated_at"
    t.string   "concept_img2_file_name"
    t.string   "concept_img2_content_type"
    t.integer  "concept_img2_file_size"
    t.datetime "concept_img2_updated_at"
    t.string   "concept_img3_file_name"
    t.string   "concept_img3_content_type"
    t.integer  "concept_img3_file_size"
    t.datetime "concept_img3_updated_at"
    t.string   "concept_img4_file_name"
    t.string   "concept_img4_content_type"
    t.integer  "concept_img4_file_size"
    t.datetime "concept_img4_updated_at"
    t.string   "concept_img5_file_name"
    t.string   "concept_img5_content_type"
    t.integer  "concept_img5_file_size"
    t.datetime "concept_img5_updated_at"
    t.string   "rent_slideshow_img1_file_name"
    t.string   "rent_slideshow_img1_content_type"
    t.integer  "rent_slideshow_img1_file_size"
    t.datetime "rent_slideshow_img1_updated_at"
    t.string   "rent_slideshow_img2_file_name"
    t.string   "rent_slideshow_img2_content_type"
    t.integer  "rent_slideshow_img2_file_size"
    t.datetime "rent_slideshow_img2_updated_at"
    t.string   "rent_slideshow_img3_file_name"
    t.string   "rent_slideshow_img3_content_type"
    t.integer  "rent_slideshow_img3_file_size"
    t.datetime "rent_slideshow_img3_updated_at"
    t.string   "activity_img1_file_name"
    t.string   "activity_img1_content_type"
    t.integer  "activity_img1_file_size"
    t.datetime "activity_img1_updated_at"
    t.string   "activity_img2_file_name"
    t.string   "activity_img2_content_type"
    t.integer  "activity_img2_file_size"
    t.datetime "activity_img2_updated_at"
    t.string   "activity_img3_file_name"
    t.string   "activity_img3_content_type"
    t.integer  "activity_img3_file_size"
    t.datetime "activity_img3_updated_at"
    t.string   "activity_img4_file_name"
    t.string   "activity_img4_content_type"
    t.integer  "activity_img4_file_size"
    t.datetime "activity_img4_updated_at"
    t.string   "activity_img5_file_name"
    t.string   "activity_img5_content_type"
    t.integer  "activity_img5_file_size"
    t.datetime "activity_img5_updated_at"
    t.string   "food_img1_file_name"
    t.string   "food_img1_content_type"
    t.integer  "food_img1_file_size"
    t.datetime "food_img1_updated_at"
    t.string   "food_img2_file_name"
    t.string   "food_img2_content_type"
    t.integer  "food_img2_file_size"
    t.datetime "food_img2_updated_at"
    t.string   "food_img3_file_name"
    t.string   "food_img3_content_type"
    t.integer  "food_img3_file_size"
    t.datetime "food_img3_updated_at"
  end

end
